/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IH:\Nim\lib -o c:\experiments\365_programs\2017-02-25\nimcache\stdlib_hashes.o c:\experiments\365_programs\2017-02-25\nimcache\stdlib_hashes.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(NI, HEX21HEX26_110004_213663784)(NI h0, NI val0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_110027_213663784)(NI h0);
N_NIMCALL(NI, hashdata_110049_213663784)(void* data0, NI size0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
static N_INLINE(NI, hash_110401_213663784)(void* x0);
static N_INLINE(NI, hash_110801_213663784)(NI x0);
static N_INLINE(NI, hash_110805_213663784)(NI64 x0);
static N_INLINE(NI, hash_110809_213663784)(NIM_CHAR x0);
N_NIMCALL(NI, hash_110827_213663784)(NimStringDesc* x0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hash_110859_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0);
N_NIMCALL(NI, hashignorestyle_110892_213663784)(NimStringDesc* x0);
static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_109004_3239285623)(NCSTRING cs0, NI i0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(NI, hashignorestyle_110975_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0);
N_NIMCALL(NI, hashignorecase_111059_213663784)(NimStringDesc* x0);
N_NIMCALL(NI, hashignorecase_111130_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0);
static N_INLINE(NI, hash_111202_213663784)(NF x0);
extern TFrame* frameptr_19636_1689653243;
TNimType NTI110002; /* Hash */

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(NI, HEX21HEX26_110004_213663784)(NI h0, NI val0) {
	NI result0;
	nimfr("!&", "hashes.nim")
	result0 = (NI)0;
	nimln(53, "hashes.nim");
	result0 = (NI)((NU64)(h0) + (NU64)(val0));
	nimln(54, "hashes.nim");
	result0 = (NI)((NU64)(result0) + (NU64)((NI)((NU64)(result0) << (NU64)(((NI) 10)))));
	nimln(55, "hashes.nim");
	result0 = (NI)(result0 ^ (NI)((NU64)(result0) >> (NU64)(((NI) 6))));
	popFrame();
	return result0;
}

static N_INLINE(NI, HEX21HEX24_110027_213663784)(NI h0) {
	NI result0;
	nimfr("!$", "hashes.nim")
	result0 = (NI)0;
	nimln(60, "hashes.nim");
	result0 = (NI)((NU64)(h0) + (NU64)((NI)((NU64)(h0) << (NU64)(((NI) 3)))));
	nimln(61, "hashes.nim");
	result0 = (NI)(result0 ^ (NI)((NU64)(result0) >> (NU64)(((NI) 11))));
	nimln(62, "hashes.nim");
	result0 = (NI)((NU64)(result0) + (NU64)((NI)((NU64)(result0) << (NU64)(((NI) 15)))));
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, hashdata_110049_213663784)(void* data0, NI size0) {
	NI result0;
	NI h0;
	NCSTRING p0;
	NI i0;
	NI s0;
	nimfr("hashData", "hashes.nim")
	result0 = (NI)0;
	nimln(66, "hashes.nim");
	h0 = ((NI) 0);
	nimln(71, "hashes.nim");
	p0 = ((NCSTRING) (data0));
	nimln(72, "hashes.nim");
	i0 = ((NI) 0);
	nimln(73, "hashes.nim");
	s0 = size0;
	{
		nimln(74, "hashes.nim");
		while (1) {
			NI TMP165;
			NI TMP166;
			nimln(351, "system.nim");
			if (!(((NI) 0) < s0)) goto LA2;
			nimln(75, "hashes.nim");
			h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(p0[i0])))));
			nimln(76, "hashes.nim");
			TMP165 = addInt(i0, ((NI) 1));
			i0 = (NI)(TMP165);
			nimln(77, "hashes.nim");
			TMP166 = subInt(s0, ((NI) 1));
			s0 = (NI)(TMP166);
		} LA2: ;
	}
	nimln(78, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_110401_213663784)(void* x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(97, "hashes.nim");
	result0 = (NI)((NU64)(((NI) (x0))) >> (NU64)(((NI) 3)));
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_110801_213663784)(NI x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(109, "hashes.nim");
	result0 = x0;
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_110805_213663784)(NI64 x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(113, "hashes.nim");
	result0 = ((NI) (((NI32)(NU32)(NU64)(x0))));
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_110809_213663784)(NIM_CHAR x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(117, "hashes.nim");
	result0 = ((NI) (((NU8)(x0))));
	popFrame();
	return result0;
}

N_NIMCALL(NI, hash_110827_213663784)(NimStringDesc* x0) {
	NI result0;
	NI h0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(125, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_110841_213663784;
		NI HEX3Atmp_110852_213663784;
		NI TMP167;
		NI res_110855_213663784;
		i_110841_213663784 = (NI)0;
		HEX3Atmp_110852_213663784 = (NI)0;
		nimln(126, "hashes.nim");
		TMP167 = subInt((x0 ? x0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_110852_213663784 = (NI)(TMP167);
		nimln(1875, "system.nim");
		res_110855_213663784 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP168;
				if (!(res_110855_213663784 <= HEX3Atmp_110852_213663784)) goto LA3;
				nimln(1877, "system.nim");
				i_110841_213663784 = res_110855_213663784;
				nimln(127, "hashes.nim");
				if ((NU)(i_110841_213663784) > (NU)(x0->Sup.len)) raiseIndexError();
				h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(x0->data[i_110841_213663784])))));
				nimln(1896, "system.nim");
				TMP168 = addInt(res_110855_213663784, ((NI) 1));
				res_110855_213663784 = (NI)(TMP168);
			} LA3: ;
		}
	}
	nimln(128, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hash_110859_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0) {
	NI result0;
	NI h0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(135, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_110875_213663784;
		NI res_110888_213663784;
		i_110875_213663784 = (NI)0;
		nimln(1875, "system.nim");
		res_110888_213663784 = spos0;
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP169;
				if (!(res_110888_213663784 <= epos0)) goto LA3;
				nimln(1877, "system.nim");
				i_110875_213663784 = res_110888_213663784;
				nimln(137, "hashes.nim");
				if ((NU)(i_110875_213663784) > (NU)(sbuf0->Sup.len)) raiseIndexError();
				h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(sbuf0->data[i_110875_213663784])))));
				nimln(1896, "system.nim");
				TMP169 = addInt(res_110888_213663784, ((NI) 1));
				res_110888_213663784 = (NI)(TMP169);
			} LA3: ;
		}
	}
	nimln(138, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, ismagicidentseparatorrune_109004_3239285623)(NCSTRING cs0, NI i0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NI TMP171;
	NI TMP172;
	nimfr("isMagicIdentSeparatorRune", "etcpriv.nim")
	result0 = (NIM_BOOL)0;
	nimln(21, "etcpriv.nim");
	nimln(22, "etcpriv.nim");
	LOC1 = (NIM_BOOL)0;
	nimln(21, "etcpriv.nim");
	LOC2 = (NIM_BOOL)0;
	LOC2 = ((NU8)(cs0[i0]) == (NU8)(226));
	if (!(LOC2)) goto LA3;
	nimln(22, "etcpriv.nim");
	TMP171 = addInt(i0, ((NI) 1));
	LOC2 = ((NU8)(cs0[(NI)(TMP171)]) == (NU8)(128));
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	nimln(23, "etcpriv.nim");
	TMP172 = addInt(i0, ((NI) 2));
	LOC1 = ((NU8)(cs0[(NI)(TMP172)]) == (NU8)(147));
	LA4: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, hashignorestyle_110892_213663784)(NimStringDesc* x0) {
	NI result0;
	NI h0;
	NI i0;
	NI xlen0;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result0 = (NI)0;
	nimln(142, "hashes.nim");
	h0 = ((NI) 0);
	nimln(143, "hashes.nim");
	i0 = ((NI) 0);
	nimln(144, "hashes.nim");
	xlen0 = (x0 ? x0->Sup.len : 0);
	{
		nimln(145, "hashes.nim");
		while (1) {
			NIM_CHAR c0;
			if (!(i0 < xlen0)) goto LA2;
			nimln(146, "hashes.nim");
			if ((NU)(i0) > (NU)(x0->Sup.len)) raiseIndexError();
			c0 = x0->data[i0];
			nimln(147, "hashes.nim");
			{
				NI TMP170;
				if (!((NU8)(c0) == (NU8)(95))) goto LA5;
				nimln(148, "hashes.nim");
				TMP170 = addInt(i0, ((NI) 1));
				i0 = (NI)(TMP170);
			}
			goto LA3;
			LA5: ;
			{
				NIM_BOOL LOC8;
				NI TMP173;
				nimln(149, "hashes.nim");
				LOC8 = (NIM_BOOL)0;
				LOC8 = ismagicidentseparatorrune_109004_3239285623(x0->data, i0);
				if (!LOC8) goto LA9;
				nimln(150, "hashes.nim");
				TMP173 = addInt(i0, ((NI) 3));
				i0 = (NI)(TMP173);
			}
			goto LA3;
			LA9: ;
			{
				NI TMP175;
				nimln(152, "hashes.nim");
				{
					NI TMP174;
					nimln(1095, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA14;
					nimln(153, "hashes.nim");
					TMP174 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(TMP174), ((NI) 0), ((NI) 255)))));
				}
				LA14: ;
				nimln(154, "hashes.nim");
				h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(155, "hashes.nim");
				TMP175 = addInt(i0, ((NI) 1));
				i0 = (NI)(TMP175);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(157, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hashignorestyle_110975_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0) {
	NI result0;
	NI h0;
	NI i0;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result0 = (NI)0;
	nimln(165, "hashes.nim");
	h0 = ((NI) 0);
	nimln(166, "hashes.nim");
	i0 = spos0;
	{
		nimln(167, "hashes.nim");
		while (1) {
			NIM_CHAR c0;
			if (!(i0 <= epos0)) goto LA2;
			nimln(168, "hashes.nim");
			if ((NU)(i0) > (NU)(sbuf0->Sup.len)) raiseIndexError();
			c0 = sbuf0->data[i0];
			nimln(169, "hashes.nim");
			{
				NI TMP176;
				if (!((NU8)(c0) == (NU8)(95))) goto LA5;
				nimln(170, "hashes.nim");
				TMP176 = addInt(i0, ((NI) 1));
				i0 = (NI)(TMP176);
			}
			goto LA3;
			LA5: ;
			{
				NIM_BOOL LOC8;
				NI TMP177;
				nimln(171, "hashes.nim");
				LOC8 = (NIM_BOOL)0;
				LOC8 = ismagicidentseparatorrune_109004_3239285623(sbuf0->data, i0);
				if (!LOC8) goto LA9;
				nimln(172, "hashes.nim");
				TMP177 = addInt(i0, ((NI) 3));
				i0 = (NI)(TMP177);
			}
			goto LA3;
			LA9: ;
			{
				NI TMP179;
				nimln(174, "hashes.nim");
				{
					NI TMP178;
					nimln(1095, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA14;
					nimln(175, "hashes.nim");
					TMP178 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(TMP178), ((NI) 0), ((NI) 255)))));
				}
				LA14: ;
				nimln(176, "hashes.nim");
				h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(177, "hashes.nim");
				TMP179 = addInt(i0, ((NI) 1));
				i0 = (NI)(TMP179);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(178, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hashignorecase_111059_213663784)(NimStringDesc* x0) {
	NI result0;
	NI h0;
	nimfr("hashIgnoreCase", "hashes.nim")
	result0 = (NI)0;
	nimln(182, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_111073_213663784;
		NI HEX3Atmp_111123_213663784;
		NI TMP180;
		NI res_111126_213663784;
		i_111073_213663784 = (NI)0;
		HEX3Atmp_111123_213663784 = (NI)0;
		nimln(183, "hashes.nim");
		TMP180 = subInt((x0 ? x0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_111123_213663784 = (NI)(TMP180);
		nimln(1875, "system.nim");
		res_111126_213663784 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NIM_CHAR c0;
				NI TMP182;
				if (!(res_111126_213663784 <= HEX3Atmp_111123_213663784)) goto LA3;
				nimln(1877, "system.nim");
				i_111073_213663784 = res_111126_213663784;
				nimln(184, "hashes.nim");
				if ((NU)(i_111073_213663784) > (NU)(x0->Sup.len)) raiseIndexError();
				c0 = x0->data[i_111073_213663784];
				nimln(185, "hashes.nim");
				{
					NI TMP181;
					nimln(1095, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA6;
					nimln(186, "hashes.nim");
					TMP181 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(TMP181), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(187, "hashes.nim");
				h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(1896, "system.nim");
				TMP182 = addInt(res_111126_213663784, ((NI) 1));
				res_111126_213663784 = (NI)(TMP182);
			} LA3: ;
		}
	}
	nimln(188, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, hashignorecase_111130_213663784)(NimStringDesc* sbuf0, NI spos0, NI epos0) {
	NI result0;
	NI h0;
	nimfr("hashIgnoreCase", "hashes.nim")
	result0 = (NI)0;
	nimln(196, "hashes.nim");
	h0 = ((NI) 0);
	{
		NI i_111146_213663784;
		NI res_111198_213663784;
		i_111146_213663784 = (NI)0;
		nimln(1875, "system.nim");
		res_111198_213663784 = spos0;
		{
			nimln(1876, "system.nim");
			while (1) {
				NIM_CHAR c0;
				NI TMP184;
				if (!(res_111198_213663784 <= epos0)) goto LA3;
				nimln(1877, "system.nim");
				i_111146_213663784 = res_111198_213663784;
				nimln(198, "hashes.nim");
				if ((NU)(i_111146_213663784) > (NU)(sbuf0->Sup.len)) raiseIndexError();
				c0 = sbuf0->data[i_111146_213663784];
				nimln(199, "hashes.nim");
				{
					NI TMP183;
					nimln(1095, "system.nim");
					if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA6;
					nimln(200, "hashes.nim");
					TMP183 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
					c0 = ((NIM_CHAR) (((NI)chckRange((NI)(TMP183), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(201, "hashes.nim");
				h0 = HEX21HEX26_110004_213663784(h0, ((NI) (((NU8)(c0)))));
				nimln(1896, "system.nim");
				TMP184 = addInt(res_111198_213663784, ((NI) 1));
				res_111198_213663784 = (NI)(TMP184);
			} LA3: ;
		}
	}
	nimln(202, "hashes.nim");
	result0 = HEX21HEX24_110027_213663784(h0);
	popFrame();
	return result0;
}

static N_INLINE(NI, hash_111202_213663784)(NF x0) {
	NI result0;
	NF y0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(206, "hashes.nim");
	y0 = ((NF)(x0) + (NF)(1.0000000000000000e+000));
	nimln(207, "hashes.nim");
	result0 = (*((NI*) ((&y0))));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void) {
NTI110002.size = sizeof(NI);
NTI110002.kind = 31;
NTI110002.base = 0;
NTI110002.flags = 3;
}

