/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IH:\Nim\lib -o c:\experiments\365_programs\2017-02-25\nimcache\stdlib_tables.o c:\experiments\365_programs\2017-02-25\nimcache\stdlib_tables.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Table117010 Table117010;
typedef struct Keyvaluepairseq117013 Keyvaluepairseq117013;
typedef struct Keyvaluepair117016 Keyvaluepair117016;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Keyerror3448 Keyerror3448;
typedef struct Valueerror3446 Valueerror3446;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct Cell48104 Cell48104;
typedef struct Cellseq48120 Cellseq48120;
typedef struct Gcheap50618 Gcheap50618;
typedef struct Gcstack50616 Gcstack50616;
typedef struct Memregion30286 Memregion30286;
typedef struct Smallchunk30240 Smallchunk30240;
typedef struct Llchunk30280 Llchunk30280;
typedef struct Bigchunk30242 Bigchunk30242;
typedef struct Intset30214 Intset30214;
typedef struct Trunk30210 Trunk30210;
typedef struct Avlnode30284 Avlnode30284;
typedef struct Gcstat50614 Gcstat50614;
typedef struct Cellset48116 Cellset48116;
typedef struct Pagedesc48112 Pagedesc48112;
typedef struct Basechunk30238 Basechunk30238;
typedef struct Freecell30230 Freecell30230;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Table117010  {
Keyvaluepairseq117013* data;
NI counter;
};
struct Keyvaluepair117016 {
NI Field0;
NI Field1;
NI Field2;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3446  {
  Exception Sup;
};
struct  Keyerror3448  {
  Valueerror3446 Sup;
};
struct  Cell48104  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48120  {
NI len;
NI cap;
Cell48104** d;
};
typedef Smallchunk30240* TY30301[512];
typedef Trunk30210* Trunkbuckets30212[256];
struct  Intset30214  {
Trunkbuckets30212 data;
};
struct  Memregion30286  {
NI minlargeobj;
NI maxlargeobj;
TY30301 freesmallchunks;
Llchunk30280* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30242* freechunkslist;
Intset30214 chunkstarts;
Avlnode30284* root;
Avlnode30284* deleted;
Avlnode30284* last;
Avlnode30284* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset48116  {
NI counter;
NI max;
Pagedesc48112* head;
Pagedesc48112** data;
};
struct  Gcheap50618  {
Gcstack50616* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48120 zct;
Cellseq48120 decstack;
Cellseq48120 tempstack;
NI recgclock;
Memregion30286 region;
Gcstat50614 stat;
Cellset48116 marked;
Cellseq48120 additionalroots;
};
struct  Gcstack50616  {
Gcstack50616* prev;
Gcstack50616* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30238  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30240  {
  Basechunk30238 Sup;
Smallchunk30240* next;
Smallchunk30240* prev;
Freecell30230* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30280  {
NI size;
NI acc;
Llchunk30280* next;
};
struct  Bigchunk30242  {
  Basechunk30238 Sup;
Bigchunk30242* next;
Bigchunk30242* prev;
NI align;
NF data;
};
typedef NI TY30219[8];
struct  Trunk30210  {
Trunk30210* next;
NI key;
TY30219 bits;
};
typedef Avlnode30284* TY30291[2];
struct  Avlnode30284  {
TY30291 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc48112  {
Pagedesc48112* next;
NI key;
TY30219 bits;
};
struct  Freecell30230  {
Freecell30230* next;
NI zerofield;
};
struct Keyvaluepairseq117013 {
  TGenericSeq Sup;
  Keyvaluepair117016 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_113259_30748785)(NI hcode0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_113263_30748785)(NI hcode0);
static N_INLINE(NIM_BOOL, mustrehash_113268_30748785)(NI length0, NI counter0);
N_NIMCALL(void, failedassertimpl_91239_1689653243)(NimStringDesc* msg0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_113401_30748785)(NI h0, NI maxhash0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, rightsize_113556_30748785)(NI count0);
N_NIMCALL(NI, nextpoweroftwo_99429_1009420244)(NI x0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NIM_BOOL, ispoweroftwo_99425_1009420244)(NI x0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, TMP195)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
static N_INLINE(NI, rawget_117268_30748785)(Table117010 t0, NI key0, NI* hc0);
static N_INLINE(NI, hash_110801_213663784)(NI x0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, enlarge_117322_30748785)(Table117010* t0);
static N_INLINE(NI, rawgetknownhc_117375_30748785)(Table117010 t0, NI key0, NI hc0);
N_NIMCALL(void, rawinsert_117391_30748785)(Table117010* t0, Keyvaluepairseq117013** data0, NI key0, NI val0, NI hc0, NI h0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell48104*, usrtocell_52240_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53401_1689653243)(Cell48104* c0);
N_NOINLINE(void, addzct_52217_1689653243)(Cellseq48120* s0, Cell48104* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
STRING_LITERAL(TMP185, "\015\012  counter < length ", 21);
STRING_LITERAL(TMP193, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TMP209, "key not found: ", 15);
extern TFrame* frameptr_19636_1689653243;
TNimType NTI117016; /* KeyValuePair */
extern TNimType NTI110002; /* Hash */
extern TNimType NTI104; /* int */
TNimType NTI117013; /* KeyValuePairSeq */
TNimType NTI117010; /* Table */
extern TNimType NTI117604; /* ref KeyError */
extern TNimType NTI3448; /* KeyError */
extern Gcheap50618 gch_50658_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(NIM_BOOL, isempty_113259_30748785)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isEmpty", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(15, "tableimpl.nim");
	result0 = (hcode0 == ((NI) 0));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, isfilled_113263_30748785)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(18, "tableimpl.nim");
	nimln(343, "system.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, mustrehash_113268_30748785)(NI length0, NI counter0) {
	NIM_BOOL result0;
	NIM_BOOL LOC5;
	NI TMP186;
	NI TMP187;
	NI TMP188;
	nimfr("mustRehash", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(24, "tableimpl.nim");
	{
		if (!!((counter0 < length0))) goto LA3;
		failedassertimpl_91239_1689653243(((NimStringDesc*) &TMP185));
	}
	LA3: ;
	nimln(25, "tableimpl.nim");
	LOC5 = (NIM_BOOL)0;
	TMP186 = mulInt(length0, ((NI) 2));
	TMP187 = mulInt(counter0, ((NI) 3));
	LOC5 = ((NI)(TMP186) < (NI)(TMP187));
	if (LOC5) goto LA6;
	TMP188 = subInt(length0, counter0);
	LOC5 = ((NI)(TMP188) < ((NI) 4));
	LA6: ;
	result0 = LOC5;
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, nexttry_113401_30748785)(NI h0, NI maxhash0) {
	NI result0;
	NI TMP189;
	nimfr("nextTry", "tableimpl.nim")
	result0 = (NI)0;
	nimln(28, "tableimpl.nim");
	TMP189 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(TMP189) & maxhash0);
	popFrame();
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rightsize_113556_30748785)(NI count0) {
	NI result0;
	NI TMP190;
	NI TMP191;
	NI TMP192;
	nimfr("rightSize", "tables.nim")
	result0 = (NI)0;
	nimln(99, "tables.nim");
	TMP190 = mulInt(((NI) (count0)), ((NI) 3));
	TMP191 = divInt(((NI) ((NI)(TMP190))), ((NI) 2));
	TMP192 = addInt(((NI) ((NI)(TMP191))), ((NI) 4));
	result0 = nextpoweroftwo_99429_1009420244(((NI) ((NI)(TMP192))));
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}
N_NIMCALL(void, TMP195)(void* p, NI op) {
	Keyvaluepairseq117013* a;
	NI LOC1;
	a = (Keyvaluepairseq117013*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, inittable_117002_30748785)(NI initialsize0, Table117010* Result) {
	nimfr("initTable", "tables.nim")
	nimln(271, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ispoweroftwo_99425_1009420244(initialsize0);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_91239_1689653243(((NimStringDesc*) &TMP193));
	}
	LA4: ;
	nimln(272, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(273, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq117013*) newSeq((&NTI117013), ((NI)chckRange(initialsize0, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NI, hash_110801_213663784)(NI x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(109, "hashes.nim");
	result0 = x0;
	popFrame();
	return result0;
}

static N_INLINE(NI, rawget_117268_30748785)(Table117010 t0, NI key0, NI* hc0) {
	NI result0;
	NI h0;
	NI TMP198;
	nimfr("rawGet", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(43, "tableimpl.nim");
	(*hc0) = hash_110801_213663784(key0);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc0) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc0) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h0 = (NI)((*hc0) & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC7 = (NIM_BOOL)0;
			LOC7 = isfilled_113263_30748785(t0.data->data[h0].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field0 == (*hc0));
				if (!(LOC10)) goto LA11;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field1 == key0);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h0 = nexttry_113401_30748785(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP198 = subInt(((NI) -1), h0);
	result0 = (NI)(TMP198);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, haskey_117256_30748785)(Table117010 t0, NI key0) {
	NIM_BOOL result0;
	NI hc0;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result0 = (NIM_BOOL)0;
	hc0 = (NI)0;
	nimln(199, "tables.nim");
	nimln(347, "system.nim");
	nimln(199, "tables.nim");
	LOC1 = (NI)0;
	LOC1 = rawget_117268_30748785(t0, key0, (&hc0));
	result0 = (((NI) 0) <= LOC1);
	popFrame();
	return result0;
}

static N_INLINE(NI, rawgetknownhc_117375_30748785)(Table117010 t0, NI key0, NI hc0) {
	NI result0;
	NI h0;
	NI TMP202;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h0 = (NI)(hc0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC3 = (NIM_BOOL)0;
			LOC3 = isfilled_113263_30748785(t0.data->data[h0].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field0 == hc0);
				if (!(LOC6)) goto LA7;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field1 == key0);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h0 = nexttry_113401_30748785(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP202 = subInt(((NI) -1), h0);
	result0 = (NI)(TMP202);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, rawinsert_117391_30748785)(Table117010* t0, Keyvaluepairseq117013** data0, NI key0, NI val0, NI hc0, NI h0) {
	nimfr("rawInsert", "tableimpl.nim")
	nimln(58, "tableimpl.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	(*data0)->data[h0].Field1 = key0;
	nimln(59, "tableimpl.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	(*data0)->data[h0].Field2 = val0;
	nimln(60, "tableimpl.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	(*data0)->data[h0].Field0 = hc0;
	popFrame();
}

N_NIMCALL(void, enlarge_117322_30748785)(Table117010* t0) {
	Keyvaluepairseq117013* n0;
	NI TMP201;
	Keyvaluepairseq117013* LOC1;
	nimfr("enlarge", "tables.nim")
	n0 = (Keyvaluepairseq117013*)0;
	nimln(237, "tables.nim");
	TMP201 = mulInt(((*t0).data ? (*t0).data->Sup.len : 0), ((NI) 2));
	n0 = (Keyvaluepairseq117013*) newSeq((&NTI117013), ((NI)chckRange((NI)(TMP201), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(238, "tables.nim");
	LOC1 = (Keyvaluepairseq117013*)0;
	LOC1 = (*t0).data;
	unsureAsgnRef((void**) (&(*t0).data), n0);
	n0 = LOC1;
	{
		NI i_117373_30748785;
		NI HEX3Atmp_117414_30748785;
		NI res_117417_30748785;
		i_117373_30748785 = (NI)0;
		HEX3Atmp_117414_30748785 = (NI)0;
		nimln(239, "tables.nim");
		HEX3Atmp_117414_30748785 = (n0 ? (n0->Sup.len-1) : -1);
		nimln(1875, "system.nim");
		res_117417_30748785 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP204;
				if (!(res_117417_30748785 <= HEX3Atmp_117414_30748785)) goto LA4;
				nimln(1877, "system.nim");
				i_117373_30748785 = res_117417_30748785;
				nimln(240, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j0;
					NI LOC10;
					NI TMP203;
					if ((NU)(i_117373_30748785) >= (NU)(n0->Sup.len)) raiseIndexError();
					LOC7 = (NIM_BOOL)0;
					LOC7 = isfilled_113263_30748785(n0->data[i_117373_30748785].Field0);
					if (!LOC7) goto LA8;
					nimln(241, "tables.nim");
					if ((NU)(i_117373_30748785) >= (NU)(n0->Sup.len)) raiseIndexError();
					if ((NU)(i_117373_30748785) >= (NU)(n0->Sup.len)) raiseIndexError();
					LOC10 = (NI)0;
					LOC10 = rawgetknownhc_117375_30748785((*t0), n0->data[i_117373_30748785].Field1, n0->data[i_117373_30748785].Field0);
					TMP203 = subInt(((NI) -1), LOC10);
					j0 = (NI)(TMP203);
					nimln(242, "tables.nim");
					if ((NU)(i_117373_30748785) >= (NU)(n0->Sup.len)) raiseIndexError();
					if ((NU)(i_117373_30748785) >= (NU)(n0->Sup.len)) raiseIndexError();
					if ((NU)(i_117373_30748785) >= (NU)(n0->Sup.len)) raiseIndexError();
					rawinsert_117391_30748785(t0, (&(*t0).data), n0->data[i_117373_30748785].Field1, n0->data[i_117373_30748785].Field2, n0->data[i_117373_30748785].Field0, j0);
				}
				LA8: ;
				nimln(1891, "system.nim");
				TMP204 = addInt(res_117417_30748785, ((NI) 1));
				res_117417_30748785 = (NI)(TMP204);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_117286_30748785)(Table117010* t0, NI key0, NI val0) {
	NI hc0;
	NI index0;
	nimfr("[]=", "tables.nim")
	hc0 = (NI)0;
	nimln(92, "tableimpl.nim");
	index0 = rawget_117268_30748785((*t0), key0, (&hc0));
	nimln(93, "tableimpl.nim");
	{
		nimln(347, "system.nim");
		if (!(((NI) 0) <= index0)) goto LA3;
		nimln(93, "tableimpl.nim");
		if ((NU)(index0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
		(*t0).data->data[index0].Field2 = val0;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP205;
		NI TMP206;
		nimln(83, "tableimpl.nim");
		{
			NIM_BOOL LOC8;
			nimln(84, "tables.nim");
			LOC8 = (NIM_BOOL)0;
			LOC8 = mustrehash_113268_30748785(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
			if (!LOC8) goto LA9;
			nimln(84, "tableimpl.nim");
			enlarge_117322_30748785(t0);
			nimln(85, "tableimpl.nim");
			index0 = rawgetknownhc_117375_30748785((*t0), key0, hc0);
		}
		LA9: ;
		nimln(86, "tableimpl.nim");
		TMP205 = subInt(((NI) -1), index0);
		index0 = (NI)(TMP205);
		nimln(87, "tableimpl.nim");
		rawinsert_117391_30748785(t0, (&(*t0).data), key0, val0, hc0, index0);
		nimln(88, "tableimpl.nim");
		TMP206 = addInt((*t0).counter, ((NI) 1));
		(*t0).counter = (NI)(TMP206);
	}
	LA1: ;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	memcpy(((NCSTRING) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((NCSTRING) ((*src0).data)), (NI)((*src0).Sup.len + ((NI) 1)));
	(*dest0).Sup.len += (*src0).Sup.len;
}

static N_INLINE(Cell48104*, usrtocell_52240_1689653243)(void* usr0) {
	Cell48104* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell48104*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell48104*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell48104))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53401_1689653243)(Cell48104* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_52217_1689653243((&gch_50658_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell48104* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_52240_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell48104* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_52240_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_53401_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI*, HEX5BHEX5D_117467_30748785)(Table117010* t0, NI key0) {
	NI* result0;
	NI hc_117480_30748785;
	NI index_117482_30748785;
	nimfr("[]", "tables.nim")
	result0 = (NI*)0;
	hc_117480_30748785 = (NI)0;
	nimln(110, "tables.nim");
	index_117482_30748785 = rawget_117268_30748785((*t0), key0, (&hc_117480_30748785));
	nimln(111, "tables.nim");
	{
		nimln(347, "system.nim");
		if (!(((NI) 0) <= index_117482_30748785)) goto LA3;
		nimln(111, "tables.nim");
		if ((NU)(index_117482_30748785) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
		result0 = (&(*t0).data->data[index_117482_30748785].Field2);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror3448* e_117603_30748785;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		e_117603_30748785 = (Keyerror3448*)0;
		nimln(2514, "system.nim");
		e_117603_30748785 = (Keyerror3448*) newObj((&NTI117604), sizeof(Keyerror3448));
		(*e_117603_30748785).Sup.Sup.Sup.m_type = (&NTI3448);
		nimln(2515, "system.nim");
		nimln(114, "tables.nim");
		LOC6 = (NimStringDesc*)0;
		LOC7 = (NimStringDesc*)0;
		LOC7 = nimIntToStr(key0);
		LOC6 = rawNewString(LOC7->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP209));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_117603_30748785).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_117603_30748785, "KeyError");
	}
	LA1: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TMP194[3];
static TNimNode* TMP196[2];
static TNimNode TMP140[7];
NTI117016.size = sizeof(Keyvaluepair117016);
NTI117016.kind = 18;
NTI117016.base = 0;
NTI117016.flags = 3;
TMP194[0] = &TMP140[1];
TMP140[1].kind = 1;
TMP140[1].offset = offsetof(Keyvaluepair117016, Field0);
TMP140[1].typ = (&NTI110002);
TMP140[1].name = "Field0";
TMP194[1] = &TMP140[2];
TMP140[2].kind = 1;
TMP140[2].offset = offsetof(Keyvaluepair117016, Field1);
TMP140[2].typ = (&NTI104);
TMP140[2].name = "Field1";
TMP194[2] = &TMP140[3];
TMP140[3].kind = 1;
TMP140[3].offset = offsetof(Keyvaluepair117016, Field2);
TMP140[3].typ = (&NTI104);
TMP140[3].name = "Field2";
TMP140[0].len = 3; TMP140[0].kind = 2; TMP140[0].sons = &TMP194[0];
NTI117016.node = &TMP140[0];
NTI117013.size = sizeof(Keyvaluepairseq117013*);
NTI117013.kind = 24;
NTI117013.base = (&NTI117016);
NTI117013.flags = 2;
NTI117013.marker = TMP195;
NTI117010.size = sizeof(Table117010);
NTI117010.kind = 18;
NTI117010.base = 0;
NTI117010.flags = 2;
TMP196[0] = &TMP140[5];
TMP140[5].kind = 1;
TMP140[5].offset = offsetof(Table117010, data);
TMP140[5].typ = (&NTI117013);
TMP140[5].name = "data";
TMP196[1] = &TMP140[6];
TMP140[6].kind = 1;
TMP140[6].offset = offsetof(Table117010, counter);
TMP140[6].typ = (&NTI104);
TMP140[6].name = "counter";
TMP140[4].len = 2; TMP140[4].kind = 2; TMP140[4].sons = &TMP196[0];
NTI117010.node = &TMP140[4];
}

