/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IH:\Nim\lib -o c:\experiments\365_programs\2017-02-25\nimcache\stdlib_strutils.o c:\experiments\365_programs\2017-02-25\nimcache\stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct Slice90651 Slice90651;
struct  Slice90651  {
NI a;
NI b;
};
static N_INLINE(NIM_BOOL, contains_107475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_107485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_107650_1689653243)(Slice90651 s0, NI value0);
N_NIMCALL(NF, round_107661_1009420244)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_107691_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_107701_1689653243)(NF* x0, NF y0);
extern TFrame* frameptr_19636_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(NI, find_107485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_107519_1689653243;
		NI i_107532_1689653243;
		i_107519_1689653243 = (NIM_CHAR)0;
		nimln(1966, "system.nim");
		i_107532_1689653243 = ((NI) 0);
		{
			nimln(1967, "system.nim");
			while (1) {
				NI TMP159;
				NI TMP160;
				if (!(i_107532_1689653243 < a0Len0)) goto LA3;
				nimln(1968, "system.nim");
				if ((NU)(i_107532_1689653243) >= (NU)(a0Len0)) raiseIndexError();
				i_107519_1689653243 = a0[i_107532_1689653243];
				nimln(2191, "system.nim");
				{
					if (!((NU8)(i_107519_1689653243) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2192, "system.nim");
				TMP159 = addInt(result0, ((NI) 1));
				result0 = (NI)(TMP159);
				nimln(1969, "system.nim");
				TMP160 = addInt(i_107532_1689653243, ((NI) 1));
				i_107532_1689653243 = (NI)(TMP160);
			} LA3: ;
		}
	}
	nimln(2193, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_107475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2198, "system.nim");
	nimln(346, "system.nim");
	nimln(347, "system.nim");
	nimln(2198, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_107485_1689653243(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_107650_1689653243)(Slice90651 s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1093, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_107691_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3324, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_107701_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3314, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

